//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPlug.Ext.FileImporter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiPlug.Ext.FileImporter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///    &lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///        &lt;div class=&quot;row-fluid&quot;&gt;
        ///            &lt;div class=&quot;box&quot;&gt;
        ///                &lt;div class=&quot;span4&quot;&gt;
        ///                &lt;/div&gt;
        ///                &lt;div class=&quot;span4&quot;&gt;
        ///                    &lt;p style=&quot;font-size:26px; line-height: 54px; text-align: center; margin: 0px;&quot;&gt;File Importer&lt;/p&gt;
        ///                &lt;/div&gt;
        ///                &lt;div class=&quot;span4&quot; style=&quot;text-align: right;&quot;&gt;
        ///                &lt;/div&gt;
        ///            &lt;/div&gt;
        ///        &lt;/div&gt;
        ///
        ///        @fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppFileImporterHome {
            get {
                return ResourceManager.GetString("AppFileImporterHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function NewFile() {
        ///    return &apos;&lt;tr&gt;\
        ///                &lt;td class=&quot;span11&quot;&gt;&lt;input class=&quot;input-block-level&quot; type=&quot;text&quot; name=&quot;Type&quot; value=&quot;&quot; placeholder=&quot;File Type&quot;&gt;&lt;/td&gt;\
        ///                &lt;td class=&quot;span1&quot;&gt;&lt;a class=&quot;btn btn-red btn-deletefiletemp&quot; href=&quot;#&quot;&gt;&lt;i class=&quot;icon-trash&quot;&gt;&lt;/i&gt;&lt;/a&gt;&lt;/td&gt;\
        ///            &lt;/tr&gt;&apos;
        ///}
        ///
        ///$(&quot;#btn-newfile&quot;).click(function () {
        ///    $(&apos;#filesTable tr:last&apos;).before(NewFile());
        ///
        ///    $(&quot;.btn-deletefiletemp&quot;).click(function (event) {
        ///        event.preventDefault();
        ///        $(th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FilesJs {
            get {
                return ResourceManager.GetString("FilesJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Not Found&lt;/h3&gt;.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@Include(&quot;MultiPlug.Ext.FileImporter.FileImporter_Settings_NavBar&quot;)
        ///&lt;section class=&quot;row-fluid&quot;&gt;
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;span12&quot;&gt;
        ///            &lt;h3 class=&quot;box-header&quot;&gt;About FileImporter&lt;a href=&quot;#&quot; class=&quot;box-collapse pull-right&quot;&gt;hide&amp;nbsp;&amp;nbsp;&lt;i class=&quot;icon-caret-up&quot;&gt;&lt;/i&gt;&lt;/a&gt;&lt;a href=&quot;#&quot; class=&quot;box-expand pull-right&quot; style=&quot;display: none&quot;&gt;show&amp;nbsp;&amp;nbsp;&lt;i class=&quot;icon-caret-down&quot;&gt;&lt;/i&gt;&lt;/a&gt;&lt;/h3&gt;
        ///            &lt;div class=&quot;box&quot;&gt;
        ///                &lt;div [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsAbout {
            get {
                return ResourceManager.GetString("SettingsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@Include(&quot;MultiPlug.Ext.FileImporter.FileImporter_Settings_NavBar&quot;)
        ///
        ///&lt;form action=&quot;&quot; method=&quot;post&quot; accept-charset=&quot;utf-8&quot; enctype=&quot;application/x-www-form-urlencoded&quot; autocomplete=&quot;off&quot;&gt;
        ///    &lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///        &lt;div class=&quot;row-fluid&quot;&gt;
        ///            &lt;div class=&quot;box&quot;&gt;
        ///                &lt;div class=&quot;span4&quot;&gt;
        ///                &lt;/div&gt;
        ///                &lt;div class=&quot;span4&quot;&gt;
        ///                    &lt;p style=&quot;font-size:26px; line-height: 54px; text-align: center; margi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsFile {
            get {
                return ResourceManager.GetString("SettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///&lt;form action=&quot;&quot; method=&quot;post&quot; accept-charset=&quot;utf-8&quot; enctype=&quot;application/x-www-form-urlencoded&quot; autocomplete=&quot;off&quot;&gt;
        ///    &lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///        &lt;div class=&quot;row-fluid&quot;&gt;
        ///            &lt;div class=&quot;box&quot;&gt;
        ///                &lt;div class=&quot;span4&quot;&gt;
        ///                &lt;/div&gt;
        ///                &lt;div class=&quot;span4&quot;&gt;
        ///                    &lt;p style=&quot;font-size:26px; line-height: 54px; text-align: center; margin: 0px;&quot;&gt;File Importer&lt;/p&gt;
        ///                &lt;/div&gt;
        ///                &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsHome {
            get {
                return ResourceManager.GetString("SettingsHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@functions {
        ///    public string NavLocationIsHome()
        ///    {
        ///        return Model.Context.Paths.Current == Model.Context.Paths.Home ? &quot;active&quot; : string.Empty;
        ///    }
        ///
        ///    public string NavLocationIsAbout()
        ///    {
        ///        return Model.Context.Paths.Current == Model.Context.Paths.Home + &quot;about/&quot; ? &quot;active&quot; : string.Empty;
        ///    }
        ///}
        ///
        ///&lt;div class=&quot;row-fluid&quot;&gt;
        ///    &lt;ul class=&quot;nav nav-tabs&quot;&gt;
        ///        &lt;li class=&quot;@NavLocationIsHome()&quot;&gt;&lt;a href=&quot;@Raw(Model.Context.Paths.Home)&quot;&gt;H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsNavBar {
            get {
                return ResourceManager.GetString("SettingsNavBar", resourceCulture);
            }
        }
    }
}
